### ISSUE TITLE
[BUG] An issue with renderin some default theme texts

### ISSUE THREAD

**Issue by Teebor-Choka** [dillonzq/LoveIt#364]
### Describe the bug 描述你遇到的错误

Random elements of the webpage seem to be formatted or rendered incorrectly, producing e.g.
```
%!(EXTRA string=Hugo) | - LoveIt
%!(EXTRA string=posts)
%!(EXTRA string=tags)
%!(EXTRA string=categories)
```

### Expected behavior 期待的行为

The text is rendered correctly as
```
Hugo
posts
tags
catagories
```

### Screenshots 屏幕截图

https://ibb.co/HYW91Mj
https://ibb.co/rsTxXnd

### Build Environment 构建环境

- OS: Ubuntu
- Theme version/commit [0.2.7, b30fc82520a488f2d644c37ffbba9a7e63f20e98]
- Hugo version [0.70.0]

Hugo Static Site Generator v0.70.0 linux/amd64 BuildDate: 2020-05-13T17:31:37Z

### Preview Environment 预览环境

- OS: Ubuntu
- Browser Firefox

### Additional Information 补充信息

Probably related to some configuration?

**Comment by dillonzq** [comment]
@Teebor-Choka fixed in #366

**Comment by Teebor-Choka** [comment]
I checked out the fix, but the problem remains... for both the menu item name... and the Hugo copyright in the footer.

**Comment by dillonzq** [comment]
Hi, @Teebor-Choka
I have changed solution of the i18n format string in #371.
This problem should have been fixed.

**Comment by Teebor-Choka** [comment]
Hi, @dillonzq, thanks. I checked out the `develop` branch. The formatting is correct, but the texts are  totally missing (e.g. `Hugo` footer text disappeared completely even with this setting on).

```
[params.footer]
    enable = true
    custom = ''
    hugo = true
    copyright = true
```

**Comment by dillonzq** [comment]
@Teebor-Choka Have you tested using other versions of Hugo?

**Comment by dillonzq** [comment]
@Teebor-Choka What is the value of `defaultContentLanguage` in your config?
I think this may be the cause of the problem.

**Comment by Teebor-Choka** [comment]
> @Teebor-Choka What is the value of `defaultContentLanguage` in your config?
> I think this may be the cause of the problem.

en-us

**Comment by Teebor-Choka** [comment]
> @Teebor-Choka Have you tested using other versions of Hugo?
> What's the language used?
> I have never reproduced this problem on Linux or macOS.

I'm using the Canonical packed snap package, 0.70 on Ubuntu 18.04, see the bug description for more details.

**Comment by dillonzq** [comment]
> > @Teebor-Choka What is the value of `defaultContentLanguage` in your config?
> > I think this may be the cause of the problem.
> 
> en-us

Replace `en-us` with `en` and set `languageCode = en-US`

**Comment by Teebor-Choka** [comment]
Indeed that helped, thanks.

**Comment by dillonzq** [comment]
@Teebor-Choka You can refer to:
https://hugoloveit.com/theme-documentation-basics/#language-compatibility

`defaultContentLanguage` should be set to Hugo code row.
And `languageCode` could be set to HTML lang Attribute row.
